server:
  port: 8082
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hotelservices
    username: postgres
    password: root
    
  jpa: 
   hibernate: 
      ddl-auto: update
   show-sql: true
  application:
    name: HOTEL-SERVICES
    
  config:
    import:
    - configserver:http://localhost:8085
  zipkin:
    base-url: http://localhost:9411/
   
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true

# Okta cinfig

okta:
  oauth2:
    issuer: https://dev-66693851.okta.com/oauth2/default
    audience: api://default
    